services:
  - type: web
    name: docuflow-api
    runtime: python
    region: oregon
    plan: starter
    rootDir: backend
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:$PORT --timeout 120
    healthCheckPath: /health
    autoDeploy: true

    envVars:
      - key: APP_ENV
        value: production
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: S3_ENDPOINT_URL
        sync: false
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: S3_BUCKET_NAME
        sync: false